src/Entity/Marque.php
<?php

namespace App\Entity;

use App\Repository\MarqueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: MarqueRepository::class)]
class Marque
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateDeCreation = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo = null;

    #[ORM\OneToMany(mappedBy: 'marque', targetEntity: Modele::class, orphanRemoval: true)]
    private Collection $modeles;

    public function __construct()
    {
        $this->modeles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDateDeCreation(): ?\DateTimeInterface
    {
        return $this->dateDeCreation;
    }

    public function setDateDeCreation(\DateTimeInterface $dateDeCreation): static
    {
        $this->dateDeCreation = $dateDeCreation;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }


    #[ORM\PostRemove]
    public function deleteLogo(){
        if ($this->logo != null){
            unlink(__DIR__ . '/../../public/logos/' . $this->logo);
        }
        return true;
    }

    /**
     * @return Collection<int, Modele>
     */
    public function getModeles(): Collection
    {
        return $this->modeles;
    }

    public function addModele(Modele $modele): static
    {
        if (!$this->modeles->contains($modele)) {
            $this->modeles->add($modele);
            $modele->setMarque($this);
        }

        return $this;
    }

    public function removeModele(Modele $modele): static
    {
        if ($this->modeles->removeElement($modele)) {
            // set the owning side to null (unless already changed)
            if ($modele->getMarque() === $this) {
                $modele->setMarque(null);
            }
        }

        return $this;
    }
}

src/Form/MarqueType.php
<?php

namespace App\Form;

use App\Entity\Marque;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class MarqueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('dateDeCreation', DateType::class, [
                'label' => 'Date de création',
            ])
            ->add('logo', FileType::class, [
                'label' => 'Image (jpg, png)',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpg',
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Enregistrer une image valide svp (jpg, png)',
                    ])
                ],
            ])
            ->add('Envoyer', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Marque::class,
        ]);
    }
}

src/Controller/MarqueController.php
<?php

namespace App\Controller;

use App\Entity\Marque;
use App\Form\MarqueType;
use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Util\Filesystem;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/marque')]
class MarqueController extends AbstractController
{
    #[Route('/', name: 'app_marque')]
    public function index(EntityManagerInterface $em, Request $request): Response
    {

        $marque = new Marque();
        $form = $this->createForm(MarqueType::class, $marque);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $imageFile = $form->get('logo')->getData();

            if ($imageFile) {
                $newFilename = uniqid().'.'.$imageFile->guessExtension();

                try {
                    $imageFile->move(
                        $this->getParameter('upload_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash('danger', 'Erreur lors de l\'import de votre logo');
                }
                $marque->setLogo($newFilename);
            }

            $em->persist($marque);
            $em->flush();

            $this->addFlash('success', 'Marque ajoutée');
        }

        $marques = $em->getRepository(Marque::class)->findAll();
        return $this->render('marque/index.html.twig', [
            'marques' => $marques,
            'ajout' => $form->createView()
        ]);
    }

    #[Route('/{id}', name: 'app_marque_show')]
    public function show(Marque $marque = null) : Response
    {

        if ($marque == null){
            $this->addFlash('danger', 'Marque introuvable');
            return $this->redirectToRoute('app_marque');
        }

        return $this->render('marque/show.html.twig', [
            'marque' => $marque,
        ]);
    }

        #[Route('/edit/{id}', name: 'app_marque_edit')]
        public function editCat(EntityManagerInterface $em, Marque $marque, Request $request)
        {
            $form = $this->createForm(MarqueType::class, $marque);

            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()){
                $imageFile = $form->get('logo')->getData();

                if ($imageFile) {
                    $newFilename = uniqid().'.'.$imageFile->guessExtension();

                    try {
                        $imageFile->move(
                            $this->getParameter('upload_directory'),
                            $newFilename
                        );

                        if ($marque->getLogo() != null){
                            unlink($this->getParameter('upload_directory') . $marque->getLogo());
                        }
                    } catch (FileException $e) {
                        $this->addFlash('danger', 'Erreur lors de l\'import de votre logo');
                    }
                    $marque->setLogo($newFilename);
                }
                $em->persist($marque);
                $em->flush();

                $this->addFlash('success', 'Marque editée');
                return $this->redirectToRoute('app_marque');
            }
            return $this->render('marque/edit.html.twig', [
                'edit' => $form->createView(),
            ]);
        }


        #[Route('/delete/{id}', name: 'app_marque_delete')]
        public function delete(Marque $marque = null, EntityManagerInterface $entityManager)
        {
            if ($marque == null){
                $this->addFlash('danger', 'Marque introuvable');
                return $this->redirectToRoute('app_marque');
            }

            $entityManager->remove($marque);
            $entityManager->flush();

            $this->addFlash('success', 'Marque supprimée');
            return $this->redirectToRoute('app_marque');
        }
}

templates/marque/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit{% endblock %}

{% block body %}
    <h1> Edit Marque</h1>

    {{ form(edit) }}
{% endblock %}

templates/marque/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Index Marque {% endblock %}

{% block body %}
    <h1>Liste des marques</h1>
    {% if marques is not empty%}
        <table class="table">
            <thead>
            <tr>
                <th>Nom</th>
                <th>Date de création</th>
                <th>Logo</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for marque in marques %}
                <tr>
                    <th>
                        {{ marque.nom }}
                    </th>
                    <th>{{ marque.dateDeCreation|date("d/m/Y") }}</th>
                    <th>
                        {% if marque.logo is not null %}
                            <img src="{{ asset('logos/' ~ marque.logo) }}" style="width:50px;" alt="{{ marque.nom }}">
                        {% else %}
                            <p>Aucun logo.</p>
                        {% endif %}
                    </th>
                    <th>
                        <a href="{{ path('app_marque_show',{'id':marque.id}) }}">
                            👀
                        </a>
                        -
                        <a href="{{ path('app_marque_edit',{'id':marque.id}) }}">
                            ⚙️
                        </a>
                        -
                        <a href="{{ path('app_marque_delete',{'id':marque.id}) }}">
                            🗑️️
                        </a>
                    </th>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Aucune marque.</p>
    {% endif %}
    <br>
    <hr>
    <br>
    <h4 class="text-center">Ajouter une marque</h4>

    {{ form(ajout) }}

{% endblock %}

templates/marque/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Show Marque {% endblock %}

{% block body %}
    <div class="card" style="width: 30vw">
        {% if marque.logo is not null %}
            <img src="{{ asset('logos/' ~ marque.logo) }}" style="width:50px;" alt="{{ marque.nom }}">
        {% endif %}
        <div class="card-body">
            <h1> {{ marque.nom }}</h1>
            <p>Description => {{ marque.dateDeCreation|date('d/m/y') }}</p>

            {% if marque.modeles is not empty %}
                <br>
                <hr>
                <br>
                <h3>Modèles associés</h3>
                {% for modele in marque.modeles %}
                    <p>
                        <a href="{{ path('app_modele_show',{'id':modele.id}) }}">
                            {{ modele.nom }}
                        </a>
                    </p>
                {% endfor %}
            {% endif %}
        </div>

    </div>
{% endblock %}